hCraft_sources = Split("""
		main.cpp
		logger.cpp
		server.cpp
		player.cpp
		playerlist.cpp
		packet.cpp
		scheduler.cpp
		entity.cpp
		position.cpp
		chunk.cpp
		world.cpp
		blocks.cpp
		worldgenerator.cpp
		flatgrass.cpp
		stringutils.cpp
		wordwrap.cpp
		threadpool.cpp
		worldprovider.cpp
		hwprovider.cpp
		utils.cpp
		rank.cpp
		permissions.cpp
		sql.cpp
		
		commands/command.cpp
		commands/help.cpp
		commands/me.cpp
		commands/ping.cpp
		commands/wcreate.cpp
		commands/world.cpp
		""")

hCraft_libs = Split("""
		pthread
		event
		m
		yaml-cpp
		z
		sqlite3
		""")

Import('env')
env.Program(target = 'hCraft', source = hCraft_sources, LIBS = hCraft_libs)

